version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: stock-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - stock-network

  mongodb:
    image: mongo:7
    container_name: stock-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: stockdb
    restart: unless-stopped
    networks:
      - stock-network

volumes:
  redis_data:
  mongodb_data:

networks:
  stock-network:
    driver: bridge
